const COUNTRY_BANKS: {
  [key: string]: string[];
} = {
  SG: [
    'Citibank',
    'DBS/POSB',
    'HSBC',
    'Maybank',
    'OCBC',
    'Standard Chartered Bank',
    'UOB',

    ' ',

    'ANZ',
    'Bangkok Bank',
    'Bank Negara Indonesia (BNI)',
    'Bank Of America',
    'Bank Of China (BOC)',
    'Bank Of India',
    'Bank Of Tokyo-Mitsubishi UFJ (MUFJ)',
    'BNP Paribas',
    'Chinatrust Commercial Bank',
    'CIMB Bank',
    'Commerzbank',
    'Crédit Agricole CIB',
    'Deutsche Bank',
    'DNB Bank Singapore',
    'Far Eastern Bank (FEB)',
    'First Commercial Bank',
    'HL Bank',
    'ICICI Bank Limited',
    'Indian Bank',
    'Indian Overseas Bank (IOB)',
    'Industrial & Commercial Bank Of China (ICBC)',
    'Intesa Sanpaolo S.P.A.',
    'JPMorgan Chase Bank (JPMC)',
    'Korea Exchange Bank (KEB)',
    'Landesbank BadenWurttemberg (LBBW)',
    'Mizuho Bank',
    'National Australia Bank(NAB)',
    'Nordea Bank',
    'RHB Bank',
    'Skandinaviska Enskilda Banken (SEB Group)',
    'Societe Generale',
    'State Bank Of India (SBI)',
    'Sumitomo Mitsui Banking Corporation (SMBC)',
    'Svenska Handelsbanken Singapore',
    'The Bank Of East Asia (BEA)',
    'The Royal Bank Of Scotland (RBS)',
    'UBS AG',
    'UCO Bank',
  ],
  JP: [
    'Mizuho Bank',
    'Sumitomo Mitsui Banking Corporation',
    'Bank of Tokyo-Mitsubishi UFJ',
    'Resona Bank',
    'Japan Post Bank',
  ],
  MY: [
    'Maybank / Malayan Banking',
    'PUBLIC BANK (L) LTD',
    'PUBLIC BANK BERHAD',
    'CIMB Bank',
    'RHB Bank',

    ' ',

    'Affin Bank',
    'Affin Islamic Bank',
    'Agro Bank / Bank Pertanian',
    'Alliance Bank',
    'Alliance Islamic Bank',
    'Ambank',
    'Aminvestment Bank',
    'Amislamic Bank',
    'Bank Islam',
    'Bank Islam (Labuan)',
    'Bank Kerjasama Rakyat / Bank Rakyat',
    'Bank Muamalat',
    'Bank of America',
    'Bank of Tokyo Mitsubishi UFJ',
    'Bank Simpanan Nasional',
    'BNP Paribas',
    'CIMB Islamic Bank',
    'CIMB Principal Asset Management',
    'Citi Bank',
    'Deutsche Bank',
    'Hong Leong Bank',
    'Hong Leong Islamic Bank',
    'HSBC Amanah',
    'HSBC Bank',
    'Idustrial and Commercial Bank of China',
    'J.P. Morgan Chase Bank',
    'Kuwait Finance House',
    'Maybank Islamic',
    'Mizuho Bank',
    'OCBC Al Amin Bank',
    'OCBC Bank (Overseas Chinese Banking Corporation)',
    'Public Islamic Bank',
    'RHB BANK (L) LTD',
    'RHB Investment Bank',
    'RHB Islamic Bank',
    'Standard Chartered Bank',
    'Standard Chartered Saadiq',
    'Sumitomo Mitsui Banking Corporation',
    'The Royal Bank of Scotland',
    'United Overseas Bank',
  ],
  ID: [
    'Bank Central Asia (BCA)',
    'Bank CIMB Niaga',
    'Bank Mandiri',
    'Bank Negara Indonesia (BNI)',
    'Bank Permata',
    'Bank Rakyat Indonesia (BRI)',
    'Citibank',
    'Hongkong and Shanghai Corporation (HSBC)',

    ' ',

    'Bank Aceh',
    'Bank Agris',
    'Bank Agroniaga',
    'Bank Andara',
    'Bank Antar Daerah',
    'Bank ANZ Indonesia',
    'Bank Artha Graha International',
    'Bank Artos Indonesia',
    'Bank Bengkulu',
    'Bank Bisnis Internasional',
    'Bank BNP Paribas',
    'Bank BPD Bali',
    'Bank BTPN Syariah',
    'Bank Bukopin',
    'Bank Bumi Arta',
    'Bank Capital',
    'Bank Centratama Nasional (CNB)',
    'Bank Commonwealth',
    'Bank CTBC Indonesia',
    'Bank Danamon Indonesia',
    'Bank DBS Indonesia',
    'Bank Dki Kc Syariah Wahid Hasyim',
    'Bank DKI',
    'Bank Fama International',
    'Bank Ganesha',
    'Bank Harda Internasional',
    'Bank ICBC Indonesia',
    'Bank Ina Perdana',
    'Bank Index Selindo',
    'Bank J Trust Indonesia (Bank Mutiara)',
    'Bank Jabar (BJB)',
    'Bank Jabar Banten Syariah',
    'Bank Jambi',
    'Bank Jasa Jakarta',
    'Bank Jateng',
    'Bank Jatim',
    'Bank Kalimantan Barat (Kalbar)',
    'Bank Kalimantan Selatan',
    'Bank Kalimantan Tengah (Kalteng)',
    'Bank Kalimantan Timur (Kaltim)',
    'Bank KEB Hana Indonesia',
    'Bank Kesejahteraan Ekonomi',
    'Bank Lampung',
    'Bank Maluku',
    'Bank Mandiri Taspen',
    'Bank Maspion',
    'Bank Mayapada International',
    'Bank Maybank Indonesia',
    'Bank Maybank Syariah Indonesia',
    'Bank Mayora',
    'Bank Mega',
    'Bank Mestika Dharma',
    'Bank MNC Internasional',
    'Bank Muamalat',
    'Bank Multiarta Sentosa',
    'Bank Nagari',
    'Bank Nationalnobu',
    'Bank Nusanara Parahyangan (BNP)',
    'Bank OCBC NISP',
    'Bank of America Merill-Lynch (BOA)',
    'Bank of China (BOC)',
    'Bank of India Indonesia',
    'Bank of Tokyo Mitsubishi UFJ (MUFG)',
    'Bank Panin Syariah',
    'Bank Panin',
    'Bank Papua',
    'Bank Pembangunan Daerah Riau (BPD)',
    'Bank Pundi Indonesia',
    'Bank QNB Indonesia',
    'Bank Rabobank International',
    'Bank Resona Perdania',
    'Bank Royal',
    'Bank Sahabat Sampoerna',
    'Bank SBI Indonesia',
    'Bank Shinhan Indonesia',
    'Bank Sinarmas',
    'Bank Standard Chartered',
    'Bank Sulselbar',
    'Bank Sulteng',
    'Bank Sultra',
    'Bank SulutGo',
    'Bank Sumitomo Mitsui Indonesia',
    'Bank Sumsel Babel',
    'Bank Sumut Syariah',
    'Bank Sumut',
    'Bank Syariah Bukopin',
    'Bank Syariah Mandiri',
    'Bank Syariah Mega',
    'Bank Tabungan Negara (BTN)',
    'Bank Tabungan Pensiunan Nasional (BTPN)',
    'Bank UOB Indonesia',
    'Bank Victoria Internasional',
    'Bank Victoria Syariah',
    'Bank Windu Kentjana (Chian Construction Bank)',
    'Bank Woori Indonesia',
    'Bank Yudha Bhakti',
    'BDP Jawa Tengah',
    'BDP Kalbar Kp Syariah Pontianak',
    'BDP Kalsel BPD Kalsel Cabang Utama',
    'BDP Sumselbabel Kc Syariah Palemban',
    'Bii kc syariah thamrin',
    'BRI Syariah',
    'BTN Kc Syariah Jakarta',
    'Daerah Istimewa Yogyakarta (DIY)',
    'Deutsche Bank Jakrta',
    'JP Morgan Chase Bank',
    'Mizuho Bank',
    'Nusa Tenggara Barat (NTB)',
    'Nusa Tenggara Timur (NTT)',
    'PRima Master Bank',
    'Royal Bank of Scotland (Jakarta)',
    'Syariah Bank Negara Indonesia (BNI Syariah)',
  ],
  TW: [
    '國泰世華商業銀行 [013]',
    '中國信託商業銀行 [822]',
    '中華郵政 [700]',
    '台北富邦銀行 [012]',
    '台新國際商業銀行 [812]',
    '玉山商業銀行 [808]',
    '臺灣中小企業銀行 [050]',
    '王道商業銀行 [048]',
    '兆豐國際商業銀行 [017]',
    '臺灣銀行 [004]',
    '臺灣土地銀行 [005]',
    '合作金庫商業銀行 [006]',
    '第一商業銀行 [007]',
    '華南商業銀行 [008]',
    '彰化商業銀行 [009]',
    '上海商業儲蓄銀行 [011]',
    '高雄銀行 [016]',
    '花旗銀行 [021]',
    '美國運通銀行 [024]',
    '首都銀行 [025]',
    '台北國際商業銀行 [051]',
    '台中商業銀行 [053]',
    '京城商業銀行 [054]',
    '滙豐商業銀行 [081]',
    '渣打國際商業銀行 [083]',
    '華泰商業銀行 [102]',
    '新光商業銀行 [103]',
    '三信商業銀行 [147]',
    '聯邦商業銀行 [803]',
    '凱基商業銀行 [809]',
    '星展銀行 [810]',
    '日盛國際商業銀行 [815]',
    '安泰商業銀 [816]',
    '樂天商業銀行 [826]',
  ],
};

export { COUNTRY_BANKS };
